/* Generic site script generated by tools/new-site.mjs — vanilla JS, no dependencies.
   Language toggle (when the page has both languages), headline word animation, reveal on scroll, counters, rotating words, install tabs + copy, typing terminal, cursor glow, magnetic buttons. */
(() => {
  'use strict';
  const $ = (s, r = document) => r.querySelector(s), $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches, coarse = matchMedia('(pointer: coarse)').matches, root = document.documentElement;
  const safe = f => { try { return f(); } catch { return null; } }, sleep = ms => new Promise(r => setTimeout(r, ms)), clamp = (x, a, b) => Math.min(b, Math.max(a, x));
  const cfg = JSON.parse($('#cfg').textContent), langs = cfg.languages || ['en'];

  /* language */
  const lb = $('#lang');
  const setLang = l => { root.lang = l; root.dir = l === 'fa' ? 'rtl' : 'ltr'; if (lb) lb.textContent = l === 'fa' ? 'English' : 'فارسی'; if (cfg.titles && cfg.titles[l]) document.title = cfg.titles[l]; safe(() => localStorage.setItem('site-lang', l)); document.dispatchEvent(new Event('langchange')); };
  if (langs.length > 1 && lb) { lb.addEventListener('click', () => setLang(root.lang === 'fa' ? 'en' : 'fa')); setLang(safe(() => localStorage.getItem('site-lang')) || ((navigator.language || '').startsWith('fa') ? 'fa' : langs[0])); } else { setLang(langs[0]); }
  const isFa = () => root.lang === 'fa';

  /* headline: words, never letters */
  const splitWords = (el, grad) => { for (const n of [...el.childNodes]) { if (n.nodeType === 3) { const f = document.createDocumentFragment(); n.textContent.split(/(\s+)/).forEach(t => { if (!t) return; if (/^\s+$/.test(t)) { f.appendChild(document.createTextNode(' ')); return; } const w = document.createElement('span'); w.className = 'w' + (grad ? ' grad' : ''); w.textContent = t; f.appendChild(w); }); n.replaceWith(f); } else if (n.nodeType === 1) splitWords(n, grad || n.classList.contains('grad')); } };
  const h1 = $('#h1'); if (h1) { $$('[lang]', h1).filter(e => e.parentElement === h1).forEach(e => splitWords(e)); $$('.grad', h1).forEach(g => { if (!g.classList.contains('w')) g.classList.remove('grad'); }); let i = 0; $$('.w', h1).forEach(w => w.style.setProperty('--i', i++ % 14)); }
  setTimeout(() => root.classList.add('go'), reduce ? 0 : 150);

  /* progress bar + nav, reveal, counters */
  const nav = $('#nav'); let lastY = 0, tick = false;
  addEventListener('scroll', () => { if (tick) return; tick = true; requestAnimationFrame(() => { tick = false; const y = scrollY, max = root.scrollHeight - innerHeight; root.style.setProperty('--sp', max > 0 ? (y / max).toFixed(4) : 0); nav.classList.toggle('hide', y > 500 && y > lastY + 4); if (y < lastY - 4 || y < 500) nav.classList.remove('hide'); lastY = y; }); }, { passive: true });
  const io = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) { e.target.classList.add('in'); io.unobserve(e.target); } }), { threshold: .12 }); $$('.rv').forEach((el, i) => { el.style.setProperty('--d', (i % 4) * 90); io.observe(el); });
  const cio = new IntersectionObserver(es => es.forEach(e => { if (!e.isIntersecting) return; cio.unobserve(e.target); const el = e.target, to = +el.dataset.count, suf = el.dataset.suffix || '', t0 = performance.now(); if (reduce) { el.textContent = to + suf; return; } (function f(now) { const p = clamp((now - t0) / 1500, 0, 1); el.textContent = Math.round(to * (1 - Math.pow(2, -10 * p))) + suf; if (p < 1) requestAnimationFrame(f); else el.textContent = to + suf; })(t0); }), { threshold: .6 }); $$('[data-count]').forEach(el => cio.observe(el));

  /* pointer effects */
  if (!coarse && !reduce) {
    const g = $('#glow'); let gx = innerWidth / 2, gy = innerHeight / 3, tx = gx, ty = gy; addEventListener('pointermove', e => { tx = e.clientX; ty = e.clientY; }, { passive: true }); (function f() { gx += (tx - gx) * .12; gy += (ty - gy) * .12; g.style.transform = `translate3d(${gx}px,${gy}px,0)`; requestAnimationFrame(f); })();
    $$('.mag').forEach(b => { b.addEventListener('pointermove', e => { const r = b.getBoundingClientRect(); b.style.transform = `translate(${(e.clientX - r.left - r.width / 2) * .22}px,${(e.clientY - r.top - r.height / 2) * .3}px)`; }); b.addEventListener('pointerleave', () => { b.style.transform = ''; }); });
    document.addEventListener('pointermove', e => { const t = e.target.closest && e.target.closest('.fcard,.pn,.qa'); if (!t) return; const r = t.getBoundingClientRect(); t.style.setProperty('--sx', (e.clientX - r.left) + 'px'); t.style.setProperty('--sy', (e.clientY - r.top) + 'px'); }, { passive: true });
  }

  /* rotating words */
  const slot = $('#rot'); if (slot && cfg.words) { let i = 0, cur = null; const show = () => { const list = cfg.words[isFa() ? 'fa' : 'en'] || cfg.words.en, s = document.createElement('span'); s.textContent = list[i % list.length]; s.className = 'pre'; slot.appendChild(s); slot.style.width = s.offsetWidth + 4 + 'px'; void s.offsetWidth; s.className = ''; if (cur) { const o = cur; o.className = 'out'; setTimeout(() => o.remove(), 700); } cur = s; i++; }; show(); if (!reduce) setInterval(show, 2300); document.addEventListener('langchange', () => { slot.innerHTML = ''; cur = null; i = 0; show(); }); }

  /* install tabs, copy, typing terminal */
  const tabs = $('#itabs'); if (tabs) tabs.addEventListener('click', e => { const b = e.target.closest('button'); if (!b) return; $$('#itabs button').forEach(x => x.setAttribute('aria-selected', x === b)); $$('.panel').forEach(p => p.classList.toggle('on', p.id === b.dataset.p)); });
  document.addEventListener('click', async e => { const b = e.target.closest('.cp'); if (!b) return; const src = b.dataset.copy ? $(b.dataset.copy) : b.parentElement.querySelector('pre'); if (!src) return; const old = b.innerHTML; try { await navigator.clipboard.writeText(src.innerText.replace(/^\$ /, '')); b.textContent = isFa() ? 'کپی شد ✓' : 'copied ✓'; } catch { b.textContent = 'Ctrl+C'; } setTimeout(() => { b.innerHTML = old; }, 1500); });
  const cmd = $('#hero-cmd'); if (cmd && cfg.heroCommand) { if (reduce) cmd.textContent = cfg.heroCommand; else (async () => { await sleep(900); for (const ch of cfg.heroCommand) { cmd.textContent += ch; await sleep(16 + Math.random() * 14); } const c = $('.caret'); if (c) c.remove(); })(); }
})();
