#!/usr/bin/env node
// gen-docs.mjs — keep the generated docs in sync with the skill.
//   node tools/gen-docs.mjs          write docs/atlas.md and copy the gallery sheets to docs/assets/gallery/
//   node tools/gen-docs.mjs --check  exit 1 if they are out of date (CI)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'), SKILL = path.join(ROOT, 'skills', 'cinewright');
const check = process.argv.includes('--check');
const { loadAtlas } = await import(pathToFileURL(path.join(SKILL, 'scripts', 'atlas-lib.mjs')).href);
const A = loadAtlas();
const stale = [];

function put(file, content) {
  const abs = path.join(ROOT, file), cur = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (cur === content) return;
  if (check) { stale.push(file); return; }
  fs.mkdirSync(path.dirname(abs), { recursive: true }); fs.writeFileSync(abs, content);
}
function copy(from, to) {
  const a = path.join(ROOT, from), b = path.join(ROOT, to);
  if (fs.existsSync(b) && fs.readFileSync(a).equals(fs.readFileSync(b))) return;
  if (check) { stale.push(to); return; }
  fs.mkdirSync(path.dirname(b), { recursive: true }); fs.copyFileSync(a, b);
}

// gallery sheets → docs/assets/gallery (GitHub Pages can only serve files under docs/)
const galleryDir = path.join(SKILL, 'references', 'gallery');
for (const f of fs.readdirSync(galleryDir).filter(f => f.endsWith('.jpg'))) copy(`skills/cinewright/references/gallery/${f}`, `docs/assets/gallery/${f}`);

const reels = new Set(fs.existsSync(path.join(ROOT, 'docs/assets/anim')) ? fs.readdirSync(path.join(ROOT, 'docs/assets/anim')) : []);
const REEL_OF = { type: 'type', 'three-d': '3d', particles: 'particles', shaders: 'shaders', looks: 'looks', logos: 'logos', graphic: 'graphic', 'ui-data': 'ui' };
const esc = s => String(s || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const short = (s, n = 150) => { s = esc(s); return s.length > n ? s.slice(0, n - 1).replace(/\s+\S*$/, '') + '…' : s; };

let md = `# The technique atlas

<!-- GENERATED by tools/gen-docs.mjs from skills/cinewright/references/atlas/*.md — edit the atlas, not this file. -->

**${A.entries.length} techniques in ${A.families.length} families.** Every entry is a short recipe (what it is for, how it works, what to avoid, what pairs with it) and, for most, **code that runs** — the CI-friendly test \`node skills/cinewright/scripts/atlas.mjs test all\` executes every one of them (${A.entries.reduce((n, e) => n + e.blocks.filter(b => ['js scene', 'js gl', 'glsl', 'js audio'].includes(b.info)).length, 0)} runnable blocks) so a recipe never rots.

Agents use the atlas through three commands; you can use them too:

\`\`\`bash
node skills/cinewright/scripts/atlas.mjs search liquid chrome 3d text   # ranked entries for what you want to do
node skills/cinewright/scripts/atlas.mjs show text3d-chrome             # the full recipe with code
node skills/cinewright/scripts/atlas.mjs clip logo-shatter-in --gif     # render it as real motion (MP4 + GIF)
\`\`\`

| family | entries | what it is |
|---|---:|---|
${A.families.map(f => `| [${f.family}](#${f.family}) | ${f.count} | ${esc(f.title.replace(/^[^—-]+[—-]\s*/, ''))} |`).join('\n')}

`;
for (const f of A.families) {
  const es = A.entries.filter(e => e.family === f.family), gal = `assets/gallery/atlas-${f.family}.jpg`, hasGal = fs.existsSync(path.join(ROOT, 'docs', gal)), reel = REEL_OF[f.family] && reels.has(`reel-${REEL_OF[f.family]}.webp`) ? `assets/anim/reel-${REEL_OF[f.family]}.webp` : null;
  md += `## ${f.family}\n\n**${esc(f.title)}**\n\n`;
  if (reel) md += `![${f.family} reel](${reel})\n\n`;
  if (hasGal) md += `<details><summary>Contact sheet — every recipe of this family at its best frame</summary>\n\n![${f.family} gallery](${gal})\n\n</details>\n\n`;
  md += `| id | title | use it for |\n|---|---|---|\n${es.map(e => `| \`${e.id}\` | ${esc(e.title)} | ${short(e.fields.use || e.fields.palette || '')} |`).join('\n')}\n\n`;
}
put('docs/atlas.md', md);

// the same catalogue as data for the website's interactive explorer
const runnable = e => e.blocks.some(b => ['js scene', 'js gl', 'glsl', 'js audio'].includes(b.info));
put('docs/assets/data/atlas.json', JSON.stringify({
  entries: A.entries.map(e => ({ id: e.id, f: e.family, t: e.title, u: (e.fields.use || e.fields.palette || '').slice(0, 240), g: e.tags.slice(0, 8), r: runnable(e) ? 1 : 0 })),
  families: A.families.map(f => ({ id: f.family, t: f.title.replace(/^[^—-]+[—-]\s*/, ''), n: f.count })),
}) + '\n');

if (check) { if (stale.length) { console.error('✘ generated docs are out of date — run: node tools/gen-docs.mjs\n  ' + stale.slice(0, 12).join('\n  ')); process.exit(1); } console.log('✔ generated docs are up to date'); }
else console.log(`✔ docs/atlas.md (${A.entries.length} entries) and docs/assets/gallery/ written`);
